package by.tc.task31.controller;

public enum CommandType {
    LOGIN,
    LOGOUT,
    REGISTER,

    SHOW_USERS,
    SHOW_REQUESTS,
    SHOW_USER_REQUESTS,
    SHOW_HOSTELS,

    DELETE_HOSTEL,
    DELETE_USER,
    DELETE_REQUEST,

    ADD_REQUEST,
    CREATE_REQUEST,

    SHOW_CREATING_FORM,

    CHANGE_REQUEST_STATUS,
    CHANGE_USER_DATA,
    CHANGE_PASSWORD,
    CHANGE_LOCALE,
    UNLOCK,
    BLOCK,
    OPEN_BLOCK_PAGE
}