package by.tc.hostel_system.controller.command;

public enum CommandType {
    ADD_REQUEST,
    APPROVE_REQUEST,
    CANCEL_REQUEST,
    CHANGE_LOCALE,
    CHANGE_PASSWORD,
    CHANGE_USER_DATA,
    CHANGE_USER_DISCOUNT,
    DELETE_USER,

    LOGIN,
    LOGOUT,
    REGISTER,

    GET_CITIES,

    SHOW_USERS,
    SHOW_HOSTELS,
    SHOW_AVAILABLE_HOSTELS,
    SHOW_REQUESTS,
    SHOW_USER_REQUESTS,
	SHOW_NEW_REQUESTS,

    UNLOCK,
    BLOCK
}